In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

In [3]:
df = pd.read_csv("Billboard1990.csv")

df.head()

     song    artist  weeks_on_chart  peak_position genre  year_end_rank
0  Song A  Artist 1            20.0            1.0   Pop            5.0
1  Song B  Artist 2            15.0            3.0  Rock           12.0
2  Song C  Artist 3            10.0           10.0   R&B           45.0
3     ...       NaN             NaN            NaN   NaN            NaN

In [4]:
le_artist = LabelEncoder()
le_genre = LabelEncoder()

df['artist'] = le_artist.fit_transform(df['artist'])
df['genre'] = le_genre.fit_transform(df['genre'])

In [8]:
df.head()

     song  artist  weeks_on_chart  peak_position  genre  year_end_rank
0  Song A       0            20.0            1.0      0            5.0
1  Song B       1            15.0            3.0      2           12.0
2  Song C       2            10.0           10.0      1           45.0
3     ...       3             NaN            NaN      3            NaN

In [13]:
from sklearn.datasets import load_iris
import pandas as pd

data = load_iris()
df = pd.DataFrame(data.data, columns=data.feature_names)
df["target"] = data.target