In [1]:
# ==============================
# 1. Import Libraries
# ==============================
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# ==============================
# 2. Load Dataset
# ==============================
df = pd.read_csv("IP.csv")

# Preview data
df.head()

      DATE  IP_YOY
0  1/31/11    4.64
1  2/28/11    3.81
2  3/31/11    4.16
3  4/30/11    3.41
4  5/31/11    2.16

In [4]:
# ==============================
# 3. Basic Info & Cleaning
# ==============================
df.info()
df.describe()

# Check missing values
df.isnull().sum()

# Fill missing values (simple approach)
df = df.ffill()

<class 'pandas.DataFrame'>
RangeIndex: 88 entries, 0 to 87
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   DATE    88 non-null     str
 1   IP_YOY  88 non-null     float64
dtypes: float64(1), str(1)
memory usage: 2.1 KB

In [5]:
# ==============================
# 4. Encode Categorical Data
# ==============================
le = LabelEncoder()

for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = le.fit_transform(df[col])

In [7]:
target_col = 'target'  # change this

if target_col in df.columns:
    X = df.drop(target_col, axis=1)
    y = df[target_col]
else:
    print("Column not found. Available columns:")
    print(df.columns)

Column not found. Available columns:
Index(['DATE', 'IP_YOY'], dtype='str')

In [12]:
print(df.columns)

Index(['DATE', 'IP_YOY'], dtype='str')

In [13]:
for col in df.columns:
    print(f"'{col}'")

'DATE'
'IP_YOY'

In [19]:
print(df.columns)
df.head()

Index(['DATE', 'IP_YOY'], dtype='str')

      DATE  IP_YOY
0  1/31/11    4.64
1  2/28/11    3.81
2  3/31/11    4.16
3  4/30/11    3.41
4  5/31/11    2.16

In [25]:
df.head()

      DATE  IP_YOY
0  1/31/11    4.64
1  2/28/11    3.81
2  3/31/11    4.16
3  4/30/11    3.41
4  5/31/11    2.16

In [28]:
print('y_test exists:', 'y_test' in globals())

y_test exists: False

In [32]:
print(hasattr(rf_model, "estimators_"))

False