In [1]:
import pandas as pd
import numpy as np

# NLP
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

# ML
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans

# Evaluation
from sklearn.metrics import silhouette_score

nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [2]:
df = pd.read_csv("Spam Email.csv")

# Preview
df.head()

   ID Mail                                               Text  Label
0   1  ham          Subject: christmas tree farm pictures\r\n      0
1   2  ham  Subject: vastar resources , inc .\r\ngary , pr...      0
2   3  ham  Subject: calpine daily gas nomination\r\n- cal...      0
3   4  ham  Subject: re : issue\r\nfyi - see note below - ...      0
4   5  ham  Subject: meter 7268 nov allocation\r\nfyi .\r\...      0

In [4]:
print(df.head())
print(df.columns.tolist())

   ID Mail                                               Text  Label
0   1  ham          Subject: christmas tree farm pictures\r\n      0
1   2  ham  Subject: vastar resources , inc .\r\ngary , pr...      0
2   3  ham  Subject: calpine daily gas nomination\r\n- cal...      0
3   4  ham  Subject: re : issue\r\nfyi - see note below - ...      0
4   5  ham  Subject: meter 7268 nov allocation\r\nfyi .\r\...      0
['ID', 'Mail', 'Text', 'Label']

In [7]:
df.columns = df.columns.str.strip()

In [9]:
df.head()

   ID Mail                                               Text  Label
0   1  ham          Subject: christmas tree farm pictures\r\n      0
1   2  ham  Subject: vastar resources , inc .\r\ngary , pr...      0
2   3  ham  Subject: calpine daily gas nomination\r\n- cal...      0
3   4  ham  Subject: re : issue\r\nfyi - see note below - ...      0
4   5  ham  Subject: meter 7268 nov allocation\r\nfyi .\r\...      0

In [14]:
print(df.columns)

Index(['ID', 'Mail', 'Text', 'Label'], dtype='str')

In [16]:
df.columns = df.columns.str.strip()

In [17]:
print(list(df.columns))

['ID', 'Mail', 'Text', 'Label']

In [18]:
print('label' in df.columns)
print('cluster' in df.columns)

False
False